var DataDict = {
			"storage_type": [{
				"id": "2230",
				"label": "仓储现货",
				"value": "0"
			}, {
				"id": "2240",
				"label": "树上果",
				"value": "1"
			}],
			"invo_form": [{
				"id": "1270",
				"label": "电子发票",
				"value": "0"
			}, {
				"id": "1280",
				"label": "纸质发票",
				"value": "1"
			}],
			"comm_state_type": [{
				"id": "950",
				"label": "销售中",
				"value": "0"
			}, {
				"id": "960",
				"label": "草稿",
				"value": "1"
			}, {
				"id": "970",
				"label": "待审核",
				"value": "2"
			}, {
				"id": "980",
				"label": "已下架",
				"value": "3"
			}, {
				"id": "990",
				"label": "被驳回",
				"value": "4"
			}],
			"sub_led_flag": [{
				"id": "2130",
				"label": "已分账",
				"value": "0"
			}, {
				"id": "2140",
				"label": "未分账",
				"value": "1"
			}],
			"set_as_cover_flag": [{
				"id": "910",
				"label": "是",
				"value": "0"
			}, {
				"id": "920",
				"label": "否",
				"value": "1"
			}],
			"bank_acct_type": [{
				"id": "210",
				"label": "对公账户",
				"value": "0"
			}, {
				"id": "220",
				"label": "对私账户",
				"value": "1"
			}],
			"order_state_type": [{
				"id": "1350",
				"label": "待确认",
				"value": "0"
			}, {
				"id": "1360",
				"label": "待付款",
				"value": "1"
			}, {
				"id": "1370",
				"label": "待发货",
				"value": "2"
			}, {
				"id": "1380",
				"label": "待收货",
				"value": "3"
			}, {
				"id": "1390",
				"label": "已完成",
				"value": "4"
			}, {
				"id": "1400",
				"label": "已取消",
				"value": "5"
			}, {
				"id": "1410",
				"label": "待自提",
				"value": "6"
			}, {
				"id": "1420",
				"label": "待评价",
				"value": "7"
			}, {
				"id": "1430",
				"label": "争议订单",
				"value": "8"
			}],
			"bill_date_type": [{
				"id": "380",
				"label": "1",
				"value": "1"
			}, {
				"id": "390",
				"label": "2",
				"value": "2"
			}, {
				"id": "400",
				"label": "3",
				"value": "3"
			}, {
				"id": "410",
				"label": "4",
				"value": "4"
			}, {
				"id": "420",
				"label": "5",
				"value": "5"
			}, {
				"id": "430",
				"label": "6",
				"value": "6"
			}, {
				"id": "440",
				"label": "7",
				"value": "7"
			}, {
				"id": "450",
				"label": "8",
				"value": "8"
			}, {
				"id": "460",
				"label": "9",
				"value": "9"
			}, {
				"id": "470",
				"label": "10",
				"value": "10"
			}, {
				"id": "480",
				"label": "11",
				"value": "11"
			}, {
				"id": "490",
				"label": "12",
				"value": "12"
			}, {
				"id": "500",
				"label": "13",
				"value": "13"
			}, {
				"id": "510",
				"label": "14",
				"value": "14"
			}, {
				"id": "520",
				"label": "15",
				"value": "15"
			}, {
				"id": "530",
				"label": "16",
				"value": "16"
			}, {
				"id": "540",
				"label": "17",
				"value": "17"
			}, {
				"id": "550",
				"label": "18",
				"value": "18"
			}, {
				"id": "560",
				"label": "19",
				"value": "19"
			}, {
				"id": "570",
				"label": "20",
				"value": "20"
			}, {
				"id": "580",
				"label": "21",
				"value": "21"
			}, {
				"id": "590",
				"label": "22",
				"value": "22"
			}, {
				"id": "600",
				"label": "23",
				"value": "23"
			}, {
				"id": "610",
				"label": "24",
				"value": "24"
			}, {
				"id": "620",
				"label": "25",
				"value": "25"
			}, {
				"id": "630",
				"label": "26",
				"value": "26"
			}, {
				"id": "640",
				"label": "27",
				"value": "27"
			}, {
				"id": "650",
				"label": "28",
				"value": "28"
			}, {
				"id": "660",
				"label": "周一",
				"value": "29"
			}, {
				"id": "670",
				"label": "周二",
				"value": "30"
			}, {
				"id": "680",
				"label": "周三",
				"value": "31"
			}, {
				"id": "690",
				"label": "周四",
				"value": "32"
			}, {
				"id": "700",
				"label": "周五",
				"value": "33"
			}, {
				"id": "710",
				"label": "周六",
				"value": "34"
			}, {
				"id": "720",
				"label": "周日",
				"value": "35"
			}],
			"exam_invo_diss_type": [{
				"id": "2110",
				"label": "无异议",
				"value": "0"
			}, {
				"id": "2120",
				"label": "有异议",
				"value": "1"
			}],
			"if_requ": [{
				"id": "1080",
				"label": "是",
				"value": "0"
			}, {
				"id": "1090",
				"label": "否",
				"value": "1"
			}],
			"cust_type": [{
				"id": "230",
				"label": "企业商户",
				"value": "0"
			}, {
				"id": "240",
				"label": "个体商户",
				"value": "1"
			}],
			"rp_state_type": [{
				"id": "2180",
				"label": "待报备",
				"value": "0"
			}, {
				"id": "2190",
				"label": "报备中",
				"value": "1"
			}, {
				"id": "2200",
				"label": "已报备",
				"value": "2"
			}],
			"proces_status_type": [{
				"id": "1580",
				"label": "已处理",
				"value": "0"
			}, {
				"id": "1590",
				"label": "未处理",
				"value": "1"
			}],
			"invo_content_type": [{
				"id": "810",
				"label": "商品明细",
				"value": "0"
			}, {
				"id": "820",
				"label": "商品类别",
				"value": "1"
			}],
			"agent_flag": [{
				"id": "190",
				"label": "是",
				"value": "0"
			}, {
				"id": "200",
				"label": "否",
				"value": "1"
			}],
			"refund_appl_state_type": [{
				"id": "1140",
				"label": "待处理",
				"value": "0"
			}, {
				"id": "1150",
				"label": "已拒绝",
				"value": "1"
			}, {
				"id": "1160",
				"label": "已完成",
				"value": "2"
			}, {
				"id": "1170",
				"label": "已取消",
				"value": "3"
			}],
			"default_flag": [{
				"id": "830",
				"label": "是",
				"value": "0"
			}, {
				"id": "840",
				"label": "否",
				"value": "1"
			}],
			"login_name_set_flag": [{
				"id": "1910",
				"label": "是",
				"value": "0"
			}, {
				"id": "1920",
				"label": "否",
				"value": "1"
			}],
			"del_flag": [{
				"id": "10",
				"label": "正常",
				"value": "0"
			}, {
				"id": "20",
				"label": "已删除",
				"value": "1"
			}],
			"memb_type": [{
				"id": "130",
				"label": "企业",
				"value": "0"
			}, {
				"id": "140",
				"label": "个体户",
				"value": "1"
			}, {
				"id": "150",
				"label": "个人",
				"value": "2"
			}, {
				"id": "160",
				"label": "员工",
				"value": "3"
			}],
			"locality_memb_type": [{
				"id": "2390",
				"label": "数字档口会员",
				"value": "1"
			}, {
				"id": "2400",
				"label": "产地会员",
				"value": "0"
			}],
			"purchase_team_state": [{
				"id": "50",
				"label": "正在关联",
				"value": "0"
			}, {
				"id": "60",
				"label": "正常采购",
				"value": "1"
			}, {
				"id": "70",
				"label": "关联失败",
				"value": "2"
			}, {
				"id": "80",
				"label": "解除绑定",
				"value": "3"
			}],
			"sf_yq_flag": [{
				"id": "1330",
				"label": "是",
				"value": "0"
			}, {
				"id": "1340",
				"label": "否",
				"value": "1"
			}],
			"settle_cycle_type": [{
				"id": "360",
				"label": "周结",
				"value": "0"
			}, {
				"id": "370",
				"label": "月结",
				"value": "1"
			}],
			"sffsdxyq_flag": [{
				"id": "30",
				"label": "是",
				"value": "0"
			}, {
				"id": "40",
				"label": "否",
				"value": "1"
			}],
			"dead_line_type": [{
				"id": "1600",
				"label": "买家提交订单后，商家确认期限",
				"value": "0"
			}, {
				"id": "1610",
				"label": "商家确认订单后，买家支付期限",
				"value": "1"
			}, {
				"id": "1620",
				"label": "买家付款后，商品提货期限",
				"value": "2"
			}, {
				"id": "1630",
				"label": "订单完成后，买家申请开票期限",
				"value": "3"
			}, {
				"id": "1640",
				"label": "订单完成后，买卖双方评价期限",
				"value": "4"
			}, {
				"id": "1650",
				"label": "账期结算单对账日后，买卖双方对账期限",
				"value": "5"
			}, {
				"id": "1660",
				"label": "账期结算单买家申请开票后，商家开票期限",
				"value": "6"
			}, {
				"id": "1670",
				"label": "账期结算单商家开票后，买家验票期限",
				"value": "7"
			}],
			"colle_meth_type": [{
				"id": "1770",
				"label": "按次",
				"value": "0"
			}, {
				"id": "1780",
				"label": "比例",
				"value": "1"
			}],
			"message_type": [{
				"id": "1500",
				"label": "系统消息",
				"value": "0"
			}, {
				"id": "1510",
				"label": "活动消息",
				"value": "1"
			}],
			"source_type": [{
				"id": "1560",
				"label": "采购小程序",
				"value": "0"
			}, {
				"id": "1570",
				"label": "商家app",
				"value": "1"
			}],
			"credit_type": [{
				"id": "750",
				"label": "正常",
				"value": "0"
			}, {
				"id": "760",
				"label": "冻结",
				"value": "1"
			}],
			"base_picture_type": [{
				"id": "2250",
				"label": "图片",
				"value": "0"
			}, {
				"id": "2260",
				"label": "视频",
				"value": "1"
			}],
			"entp_auth_state_type": [{
				"id": "320",
				"label": "已认证",
				"value": "0"
			}, {
				"id": "330",
				"label": "未认证",
				"value": "1"
			}, {
				"id": "340",
				"label": "待审核",
				"value": "2"
			}, {
				"id": "350",
				"label": "未通过",
				"value": "3"
			}],
			"password_set_flag": [{
				"id": "1930",
				"label": "是",
				"value": "0"
			}, {
				"id": "1940",
				"label": "否",
				"value": "1"
			}],
			"sf_admin_flag": [{
				"id": "890",
				"label": "是",
				"value": "0"
			}, {
				"id": "900",
				"label": "否",
				"value": "1"
			}],
			"ap_flag": [{
				"id": "1970",
				"label": "是",
				"value": "0"
			}, {
				"id": "1980",
				"label": "否",
				"value": "1"
			}],
			"effe_inval_state": [{
				"id": "850",
				"label": "启用",
				"value": "0"
			}, {
				"id": "860",
				"label": "停用",
				"value": "1"
			}],
			"if_search": [{
				"id": "1120",
				"label": "是",
				"value": "0"
			}, {
				"id": "1130",
				"label": "否",
				"value": "1"
			}],
			"if_display_type": [{
				"id": "1750",
				"label": "是",
				"value": "0"
			}, {
				"id": "1760",
				"label": "否",
				"value": "1"
			}],
			"problem_type": [{
				"id": "1520",
				"label": "功能问题",
				"value": "0"
			}, {
				"id": "1530",
				"label": "产品建议",
				"value": "1"
			}, {
				"id": "1540",
				"label": "账号问题",
				"value": "2"
			}, {
				"id": "1550",
				"label": "其他问题",
				"value": "3"
			}],
			"sf_late_fee_flag": [{
				"id": "730",
				"label": "是",
				"value": "0"
			}, {
				"id": "740",
				"label": "否",
				"value": "1"
			}],
			"acct_state": [{
				"id": "170",
				"label": "正常",
				"value": "0"
			}, {
				"id": "180",
				"label": "冻结",
				"value": "1"
			}],
			"comm_picture_type": [{
				"id": "1100",
				"label": "主图",
				"value": "0"
			}, {
				"id": "1110",
				"label": "细节图",
				"value": "1"
			}],
			"sex_type": [{
				"id": "90",
				"label": "未知",
				"value": "0"
			}, {
				"id": "100",
				"label": "男",
				"value": "1"
			}, {
				"id": "110",
				"label": "女",
				"value": "2"
			}, {
				"id": "120",
				"label": "未说明",
				"value": "9"
			}],
			"recon_state_type": [{
				"id": "2040",
				"label": "待双方对账",
				"value": "0"
			}, {
				"id": "2050",
				"label": "待买家对账",
				"value": "1"
			}, {
				"id": "2060",
				"label": "待商家对账",
				"value": "2"
			}, {
				"id": "2070",
				"label": "对账异议",
				"value": "3"
			}, {
				"id": "2080",
				"label": "对账完成",
				"value": "4"
			}],
			"rela_state_type": [{
				"id": "870",
				"label": "已添加",
				"value": "0"
			}, {
				"id": "880",
				"label": "已解除",
				"value": "1"
			}],
			"ser_support_type": [{
				"id": "1990",
				"label": "远程视频看货",
				"value": "0"
			}, {
				"id": "2000",
				"label": "不支持退货",
				"value": "1"
			}, {
				"id": "2010",
				"label": "自提现场验货",
				"value": "2"
			}, {
				"id": "2020",
				"label": "承诺在线交易",
				"value": "3"
			}, {
				"id": "2030",
				"label": "48小时内发货",
				"value": "4"
			}],
			"origin_place_type": [{
				"id": "930",
				"label": "国内产地",
				"value": "0"
			}, {
				"id": "940",
				"label": "国外产地",
				"value": "1"
			}],
			"auth_state_type": [{
				"id": "250",
				"label": "待平台审核",
				"value": "0"
			}, {
				"id": "260",
				"label": "待银盛开户",
				"value": "1"
			}, {
				"id": "280",
				"label": "审核通过",
				"value": "3"
			}, {
				"id": "290",
				"label": "审核未通过",
				"value": "4"
			}],
			"comm_attri_type": [{
				"id": "1000",
				"label": "文本",
				"value": "0"
			}, {
				"id": "1010",
				"label": "下拉框",
				"value": "1"
			}, {
				"id": "1020",
				"label": "百分数",
				"value": "2"
			}, {
				"id": "1030",
				"label": "整数",
				"value": "3"
			}, {
				"id": "1040",
				"label": "浮点数",
				"value": "4"
			}, {
				"id": "1050",
				"label": "年份",
				"value": "5"
			}, {
				"id": "1060",
				"label": "日期",
				"value": "6"
			}, {
				"id": "1070",
				"label": "时间",
				"value": "7"
			}],
			"settle_bill_statue_type": [{
				"id": "1290",
				"label": "待对账",
				"value": "0"
			}, {
				"id": "1300",
				"label": "待结算",
				"value": "1"
			}, {
				"id": "1310",
				"label": "已结算",
				"value": "2"
			}, {
				"id": "1320",
				"label": "已取消",
				"value": "3"
			}],
			"base_order_state_type": [{
				"id": "2300",
				"label": "待确认",
				"value": "0"
			}, {
				"id": "2310",
				"label": "待付款",
				"value": "1"
			}, {
				"id": "2320",
				"label": "已完成",
				"value": "2"
			}, {
				"id": "2330",
				"label": "已取消",
				"value": "3"
			}, {
				"id": "2340",
				"label": "待交货",
				"value": "4"
			}, {
				"id": "2350",
				"label": "待评价",
				"value": "5"
			}, {
				"id": "2360",
				"label": "争议订单",
				"value": "6"
			}],
			"base_type": [{
				"id": "2210",
				"label": "国内基地",
				"value": "0"
			}, {
				"id": "2220",
				"label": "国外基地",
				"value": "1"
			}],
			"scope": [{
				"id": "1810",
				"label": "全部会员",
				"value": "0"
			}, {
				"id": "1820",
				"label": "全部供应商",
				"value": "1"
			}, {
				"id": "1830",
				"label": "全部采购商",
				"value": "2"
			}, {
				"id": "1840",
				"label": "供应商企业认证会员",
				"value": "3"
			}, {
				"id": "1850",
				"label": "供应商个体工商户认证会员",
				"value": "4"
			}, {
				"id": "1860",
				"label": "采购商企业认证会员",
				"value": "5"
			}, {
				"id": "1870",
				"label": "采购商个体工商户认证会员",
				"value": "6"
			}, {
				"id": "1880",
				"label": "采购商个人认证会员",
				"value": "7"
			}],
			"settle_bill_prdut_type": [{
				"id": "2090",
				"label": "系统生成",
				"value": "0"
			}, {
				"id": "2100",
				"label": "提前结算",
				"value": "1"
			}],
			"buy_sell_flag": [{
				"id": "1200",
				"label": "买方",
				"value": "0"
			}, {
				"id": "1210",
				"label": "卖方",
				"value": "1"
			}],
			"settle_bill_generate_type": [{
				"id": "1460",
				"label": "已生成",
				"value": "0"
			}, {
				"id": "1470",
				"label": "未生成",
				"value": "1"
			}],
			"trans_type": [{
				"id": "2370",
				"label": "同城交易商品",
				"value": "0"
			}, {
				"id": "2380",
				"label": "产地交易商品",
				"value": "1"
			}],
			"entry_open_invo_type": [{
				"id": "2150",
				"label": "电子发票",
				"value": "0"
			}, {
				"id": "2160",
				"label": "邮寄发票",
				"value": "1"
			}, {
				"id": "2170",
				"label": "线下交票",
				"value": "2"
			}],
			"pay_method_type": [{
				"id": "1440",
				"label": "在线支付",
				"value": "0"
			}, {
				"id": "1450",
				"label": "账期支付",
				"value": "1"
			}],
			"handler_type": [{
				"id": "1220",
				"label": "卖方",
				"value": "0"
			}, {
				"id": "1230",
				"label": "平台",
				"value": "1"
			}],
			"invo_catg_type": [{
				"id": "790",
				"label": "个人",
				"value": "0"
			}, {
				"id": "800",
				"label": "企业",
				"value": "1"
			}],
			"seller_operat_type": [{
				"id": "1180",
				"label": "同意",
				"value": "0"
			}, {
				"id": "1190",
				"label": "拒绝",
				"value": "1"
			}],
			"discount_type": [{
				"id": "1790",
				"label": "总体折扣",
				"value": "0"
			}, {
				"id": "1800",
				"label": "重新指定",
				"value": "1"
			}],
			"entp_comm_pub_exam_type": [{
				"id": "1950",
				"label": "否",
				"value": "1"
			}],
			"read_flag": [{
				"id": "1480",
				"label": "未读",
				"value": "0"
			}, {
				"id": "1490",
				"label": "已读",
				"value": "1"
			}],
			"dimensions_type": [{
				"id": "1680",
				"label": "重量",
				"value": "0"
			}, {
				"id": "1690",
				"label": "件数",
				"value": "1"
			}, {
				"id": "1700",
				"label": "长度",
				"value": "2"
			}, {
				"id": "1710",
				"label": "面积",
				"value": "3"
			}, {
				"id": "1720",
				"label": "体积",
				"value": "4"
			}, {
				"id": "1730",
				"label": "时间",
				"value": "5"
			}, {
				"id": "1740",
				"label": "其他",
				"value": "6"
			}],
			"invo_type": [{
				"id": "770",
				"label": "普通发票",
				"value": "0"
			}, {
				"id": "780",
				"label": "增值税专用发票",
				"value": "1"
			}],
			"entp_type": [{
				"id": "300",
				"label": "采购商",
				"value": "0"
			}, {
				"id": "310",
				"label": "供应商",
				"value": "1"
			}],
			"wareh_type": [{
				"id": "2270",
				"label": "冷冻",
				"value": "0"
			}, {
				"id": "2280",
				"label": "常温",
				"value": "1"
			}, {
				"id": "2290",
				"label": "冷藏",
				"value": "2"
			}],
			"zt_address_type": [{
				"id": "1890",
				"label": "档口地址",
				"value": "0"
			}, {
				"id": "1900",
				"label": "买家指定地址",
				"value": "1"
			}],
			"invo_state": [{
				"id": "1240",
				"label": "待开票",
				"value": "0"
			}, {
				"id": "1250",
				"label": "待验票",
				"value": "1"
			}, {
				"id": "1260",
				"label": "已完成",
				"value": "2"
			}]
		}
module.exports = DataDict
